select
    (sum(case when AGE_YY is null then 1 else 0 end)/count(*) ) as age_null,
    (sum(case when FUNCTION is null then 1 else 0 end)/count(*) ) as func_null,
    (sum(case when UNIT is null then 1 else 0 end)/count(*) ) as unit_null,
    (sum(case when TENURE_MM is null then 1 else 0 end)/count(*) ) as tenure_null,
    (sum(case when TRAINING_DAYS_36M is null then 1 else 0 end)/count(*) ) as train_null,
    (sum(case when POS_CHNG_COUNT is null then 1 else 0 end)/count(*) ) as pos_null,
    (sum(case when PERF_SLOPE is null then 1 else 0 end)/count(*) ) as perf_slope_null,
    (sum(case when CURR_SCORE is null then 1 else 0 end)/count(*) ) as cur_score_null,
    (sum(case when PERF_DELTA is null then 1 else 0 end)/count(*) ) as perf_delt_null,
    (sum(case when MONTHS_SINCE_PROM is null then 1 else 0 end)/count(*) ) as months_prom_null,
    (sum(case when PROM_COUNT is null then 1 else 0 end)/count(*) ) as prom_count_null,
    (sum(case when STAGFLATION is null then 1 else 0 end)/count(*) ) as stagf_null,
    (sum(case when INCENTIVE_VOLATILITY is null then 1 else 0 end)/count(*) ) as inc_vol_null,
    (sum(case when INCENTIVE_SUM_LAST3Y is null then 1 else 0 end)/count(*) ) as inc_sum_null,
    (sum(case when RESIG_FLAG is null then 1 else 0 end)/count(*) ) as resig_flg_null,
    (sum(case when RESIG_SAME_UNIT_GRADE is null then 1 else 0 end)/count(*) ) as resig_unit_null,
    (sum(case when ABSENCE_DAYS_6M is null then 1 else 0 end)/count(*) ) as ab_6m_null,
    (sum(case when ABSENCE_RATE_3M is null then 1 else 0 end)/count(*) ) as ab_3m_null,
    (sum(case when ABSENCE_RATE_30D is null then 1 else 0 end)/count(*) ) as ab_30d_null,
    (sum(case when ABSENCE_SPIKE is null then 1 else 0 end)/count(*) ) as ab_spike_null,
    (sum(case when SAL_GROWTH is null then 1 else 0 end)/count(*) ) as sal_grth_null,
    (sum(case when COMPA_RATIO is null then 1 else 0 end)/count(*) ) as comp_rat_null,
    (sum(case when BELOW_PEER_FLAG is null then 1 else 0 end)/count(*) ) as pr_flg_null
from 
saptest.PROJECT_MONTHLY_SNAPSHOT_TB;
