--------------------------------------------------------
--  File created - Monday-March-16-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROJECT_DIM_DATE
--------------------------------------------------------

  CREATE TABLE "SAPTEST"."PROJECT_DIM_DATE" 
   (	"DATE_KEY" NUMBER(8,0), 
	"FULL_DATE" DATE, 
	"DAY_OF_MONTH" NUMBER(2,0), 
	"DAY_NAME" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"DAY_OF_WEEK_NUM" NUMBER(1,0), 
	"WEEK_OF_YEAR" NUMBER(2,0), 
	"MONTH_NUM" NUMBER(2,0), 
	"MONTH_NAME" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"MONTH_YEAR" VARCHAR2(8 BYTE) COLLATE "USING_NLS_COMP", 
	"QUARTER_NUM" NUMBER(1,0), 
	"YEAR_NUM" NUMBER(4,0), 
	"IS_WEEKEND" CHAR(1 BYTE) COLLATE "USING_NLS_COMP", 
	"MONTH_START_DATE" DATE, 
	"MONTH_END_DATE" DATE, 
	"QUARTER_START_DATE" DATE, 
	"QUARTER_END_DATE" DATE, 
	"YEAR_START_DATE" DATE, 
	"YEAR_END_DATE" DATE, 
	"FISCAL_YEAR" VARCHAR2(9 BYTE) COLLATE "USING_NLS_COMP", 
	"FISCAL_MONTH_NUM" NUMBER(2,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C001268025
--------------------------------------------------------

  CREATE UNIQUE INDEX "SAPTEST"."SYS_C001268025" ON "SAPTEST"."PROJECT_DIM_DATE" ("DATE_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_DIM_DATE_FULL_DATE
--------------------------------------------------------

  CREATE INDEX "SAPTEST"."IDX_DIM_DATE_FULL_DATE" ON "SAPTEST"."PROJECT_DIM_DATE" ("FULL_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PROJECT_DIM_DATE
--------------------------------------------------------

  ALTER TABLE "SAPTEST"."PROJECT_DIM_DATE" MODIFY ("FULL_DATE" NOT NULL ENABLE);
  ALTER TABLE "SAPTEST"."PROJECT_DIM_DATE" ADD PRIMARY KEY ("DATE_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
