--------------------------------------------------------
--  File created - Monday-March-16-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROJECT_FT_ABSENCE
--------------------------------------------------------

  CREATE TABLE "SAPTEST"."PROJECT_FT_ABSENCE" 
   (	"EMP_ID" NUMBER(8,0), 
	"SNAPSHOT_MONTH" DATE, 
	"ABSENCE_DAYS_6M" NUMBER, 
	"ABSENCE_RATE_3M" NUMBER, 
	"ABSENCE_RATE_30D" NUMBER, 
	"ABSENCE_SPIKE" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
