--------------------------------------------------------
--  File created - Monday-March-16-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROJECT_MONTHLY_SNAPSHOT_TB
--------------------------------------------------------

  CREATE TABLE "SAPTEST"."PROJECT_MONTHLY_SNAPSHOT_TB" 
   (	"EMP_ID" NUMBER(8,0), 
	"SNAPSHOT_MONTH" DATE, 
	"AGE_YY" NUMBER, 
	"FUNCTION" VARCHAR2(8 BYTE) COLLATE "USING_NLS_COMP", 
	"CADRE" VARCHAR2(8 BYTE) COLLATE "USING_NLS_COMP", 
	"GRADE" VARCHAR2(8 BYTE) COLLATE "USING_NLS_COMP", 
	"UNIT" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"LOCATION" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"TENURE_MM" NUMBER, 
	"TRAINING_DAYS_36M" NUMBER, 
	"POS_CHNG_COUNT" NUMBER, 
	"PERF_SLOPE" NUMBER, 
	"CURR_SCORE" NUMBER(6,2), 
	"PERF_DELTA" NUMBER, 
	"MONTHS_SINCE_PROM" NUMBER, 
	"PROM_COUNT" NUMBER, 
	"STAGFLATION" NUMBER, 
	"INCENTIVE_VOLATILITY" NUMBER, 
	"INCENTIVE_SUM_LAST3Y" NUMBER, 
	"RESIG_FLAG" NUMBER, 
	"RESIG_SAME_UNIT_GRADE" NUMBER, 
	"ABSENCE_DAYS_6M" NUMBER, 
	"ABSENCE_RATE_3M" NUMBER, 
	"ABSENCE_RATE_30D" NUMBER, 
	"ABSENCE_SPIKE" NUMBER, 
	"SAL_GROWTH" NUMBER, 
	"COMPA_RATIO" NUMBER, 
	"BELOW_PEER_FLAG" CHAR(1 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
